# Generated by Django 5.1.3 on 2024-12-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptiondata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=50)),
            ],
        ),
    ]
