# Generated by Django 5.1.3 on 2024-12-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_adoptiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptiondata',
            name='contact',
            field=models.CharField(max_length=30),
        ),
    ]
