# Generated by Django 5.1.3 on 2024-12-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_adoptiondata_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptiondata',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adoptiondata',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
