# Generated by Django 5.1.3 on 2024-12-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_adoptiondata_address_alter_adoptiondata_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptiondata',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='adoptiondata',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='adoptiondata',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='adoptiondata',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adoptiondata',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='adoptiondata',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
